#!/usr/bin/env bash
echo "---------------------------------------------------------"
echo "$(tput setaf 2)JARVIS: Checking for Homebrew installation.$(tput sgr 0)"
echo "---------------------------------------------------------"
brew="/opt/homebrew/bin/brew"
if [ -f "$brew" ]; then
  echo "---------------------------------------------------------"
  echo "$(tput setaf 2)JARVIS: Homebrew is installed.$(tput sgr 0)"
  echo "---------------------------------------------------------"
else
  echo "---------------------------------------------------------"
  echo "$(tput setaf 3)JARVIS: Installing Homebrew. Homebrew requires osx command lines tools, please download xcode first$(tput sgr 0)"
  echo "---------------------------------------------------------"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo "---------------------------------------------------------"
echo "$(tput setaf 2)JARVIS: Installing system packages.$(tput sgr 0)"
echo "---------------------------------------------------------"

packages=(
  "bat"
  "curl"
  "exa"
  "fd"
  "fzf"
  "gcc"
  "git"
  "gnu-sed"
  "htop"
  "lua"
  "mpv"
  "neofetch"
  "neovim"
  "node"
  "pyenv"
  "pyenv-virtualenv"
  "python3"
  "ranger"
  "ripgrep"
  "ruby"
  "starship"
  "tig"
  "tldr"
  "tmux"
  "tmuxinator"
  "wget"
  "xsel"
  "yt-dlp"
  "zsh"
)

for i in "${packages[@]}"; do
  brew install $i
  echo "---------------------------------------------------------"
done

echo "---------------------------------------------------------"
echo "$(tput setaf 2)JARVIS: Enabling keybindings and fuzzy completion for fzf.$(tput sgr 0)"
echo "---------------------------------------------------------"

[ -f ~/.fzf.zsh ] || /opt/homebrew/opt/fzf/install

echo "---------------------------------------------------------"
echo "$(tput setaf 2)JARVIS: Installing system fonts.$(tput sgr 0)"
echo "---------------------------------------------------------"

brew tap homebrew/cask-fonts
brew install font-jetbrains-mono-nerd-font font-maple
