#!/usr/bin/env bash
echo "---------------------------------------------------------"
echo "$(tput setaf 2)JARVIS: Installing python neovim client.$(tput sgr 0)"
echo "---------------------------------------------------------"

pip3 install --upgrade pynvim

echo "---------------------------------------------------------"
echo "$(tput setaf 2)JARVIS: Installing node neovim package$(tput sgr 0)"
echo "---------------------------------------------------------"

npm install -g neovim
