vim.g.neoformat_basic_format_align = 1
vim.g.neoformat_basic_format_retab = 1
vim.g.neoformat_basic_format_trim = 1
vim.g.neoformat_try_node_exe = 1
vim.g.shfmt_opt = "-ci"

vim.g.neoformat_enabled_c = { "clangformat" }
vim.g.neoformat_enabled_cpp = { "clangformat" }
vim.g.neoformat_enabled_css = { "prettier" }
vim.g.neoformat_enabled_html = { "prettier" }
vim.g.neoformat_enabled_javascript = { "prettier" }
vim.g.neoformat_enabled_json = { "prettier" }
vim.g.neoformat_enabled_less = { "prettier" }
vim.g.neoformat_enabled_lua = { "stylua" }
vim.g.neoformat_enabled_markdown = { "prettier" }
vim.g.neoformat_enabled_python = { "yapf" }
vim.g.neoformat_enabled_rust = { "rustfmt" }
vim.g.neoformat_enabled_scss = { "prettier" }
vim.g.neoformat_enabled_sh = { "shfmt" }
vim.g.neoformat_enabled_vue = { "prettier" }
vim.g.neoformat_enabled_zsh = { "shfmt" }
